apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: CertSecretStore
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /app/dapr/components/certsecrets.json
  - name: nestedSeparator
    value: ":"
  - name: multiValued
    value: "true"