# Default values for CalculatorApp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

AddService:
  name : add-service
  port: "80"
  dapr: 
    enabled: "true"
    config: "tracing"
    log_level: "debug"
    log_as_json: "true"
  Image:
      repository: koimad/add
      pullPolicy: Always

