apiVersion: apps/v1
kind: Deployment
metadata:
  name: addapp
  labels:
    app: add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add
  template:
    metadata:
      labels:
        app: add
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "addapp"
        dapr.io/app-port: "80"
        dapr.io/config: "tracing"
        dapr.io/log-level: "debug"
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - name: add
        image: koimad/add
        ports:
        - containerPort: 80
        imagePullPolicy: Always