apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtractapp
  labels:
    app: subtract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtract
  template:
    metadata:
      labels:
        app: subtract
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subtractapp"
        dapr.io/app-port: "80"
        dapr.io/config: "tracing"
        dapr.io/log-level: "debug"
        dapr.io/log-as-json: "true"       
    spec:
      containers:
      - name: subtract
        image: koimad/subtract
        ports:
        - containerPort: 80
        imagePullPolicy: Always